# vim: set filetype=Dockerfile;

FROM nginx:latest
MAINTAINER qhwa <qhwa@pnq.cc>

# 使用阿里云源
#ADD sources.list.trusty /etc/apt/sources.list
#RUN apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 40976EAF437D05B5 3B4FE6ACC0B21F32
#RUN apt-get update

# -- web
ADD web /app/web
RUN rm /etc/nginx/conf.d/*
ADD rc/nginx /etc/nginx/conf.d/

CMD ["nginx", "-g", "daemon off;"]
