web:
  dockerfile: "Dockerfile.web"
  build: .
  ports:
    - "80:80"
  links:
    - "mirror:app"
  environment:
    # fill with real gira api token
    # from gira.cc
    GIRA_API_TOKEN: ""

mirror:
  dockerfile: Dockerfile
  build: .
  ports:
    - "6000:6000"
  links:
    - "redis:redis"
    - "memcached:cache"
    - "postgres:postgres"

redis:
  image: "redis"
  ports:
    - "6379:6379"

memcached:
  image: "memcached"
  ports:
    - "11211:11211"

postgres:
  image: "postgres"
  ports:
    - "5432:5432"
