FROM nginx:latest
MAINTAINER qhwa <qhwa@pnq.cc>

# 使用阿里云源
ADD rc/sources.list.jessie /etc/apt/sources.list
RUN apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 40976EAF437D05B5 3B4FE6ACC0B21F32
RUN apt-get update

# -- web
ADD web /app/web
RUN rm /etc/nginx/conf.d/*
ADD rc/nginx /etc/nginx/conf.d/

# -- source mirrors
RUN apt-get install wget curl sudo -y
RUN mkdir /ruby_sources
ENV RUBY_SRC_UPSTREAM=http://ring.u-toyama.ac.jp/archives/lang/ruby/
ADD cron_script /app/cron

# 使用 gira 加速网络请求
ENV GIRA_API_TOKEN=""

CMD ["nginx", "-g", "daemon off;"]
