#!/usr/bin/env bash

count=`ps aux | grep mirror:update | wc -l`
if [ ${count} -lt 2 ] ; then

	echo
	echo "------- start at $(date)"
	cd /app/rubygems-mirror/ && /usr/local/bundle/bin/bundle exec rake mirror:update

	echo
	echo "------- database sync start at $(date)"

	cd /app/bundler-api/ && /usr/local/bundle/bin/bundle exec rake update[100]
	echo
	echo "------- end at $(date)"
fi
