#!/usr/bin/env sh
if [ -n "$GIRA_API_TOKEN" ]; then
  curl https://gira.cc/install | bash -s $GIRA_API_TOKEN
  gira whoami
fi

REJECT_DIRS=/archives/lang/ruby/1.0,/archives/lang/ruby/1.1a,/archives/lang/ruby/1.1b,/archives/lang/ruby/1.1c,/archives/lang/ruby/1.1d,/archives/lang/ruby/1.2,/archives/lang/ruby/1.3,/archives/lang/ruby/1.4,/archives/lang/ruby/1.6,/archives/lang/ruby/1.8,/archives/lang/ruby/binaries,/archives/lang/ruby/doc
REJECT_DIRS=""

OPTS="-m -L -P /ruby_sources -R '*.html*' -X $REJECT_DIRS"
OPTS="-m -L -P /ruby_sources -R '*.html*'"
UPSTREAM=http://cache.ruby-lang.org/pub/

if [ -n "$GIRA_API_TOKEN" ]; then
  proxychains wget $OPTS $UPSTREAM
else
  wget $OPTS $UPSTREAM
fi
